### ISSUE TITLE
Steine drehen manchmal garnicht oder in die falsche Richtung.

### ISSUE THREAD

**Issue by MrFriendzone** [lkschenk/tetris#19]

**Comment by lkschenk** [comment]
Wann kam das denn vor? Ich hab da ziemlich ausführlich getestet und hatte nie Fehler.
Sie drehen nur nicht, wenn sie dann mit anderen Steinen oder den Spielfeldrändern kollidieren würden.

**Comment by lkschenk** [comment]
Ich habs gerade getestet. Hast du was an den Tranformationen generell oder an der Drehung geändert? Der Fehler kam vorher nicht vor

**Comment by lkschenk** [comment]
Ich glaube das Problem ist, dass sich die Würfel-Achsen (Left, for) dann teils drehen und teils nicht, was zu lomischem Verhalten der Steine führt. Wir müssten die Steuerung eher in der Application Klasse ändern, vielleicht so wie du es bei der Kamera gemacht hast.
